# Generated by Django 3.1.3 on 2020-12-01 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tictac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_time', models.DateTimeField(auto_now_add=True, verbose_name='time_entered')),
                ('waiting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictac.user')),
            ],
        ),
    ]
